### ISSUE TITLE
deprecation warning gone.

### ISSUE THREAD

**Issue by jdalton** [juliangruber/isarray#12]
It looks like the bump to 2.0.1 removed the deprecation warning.
It may be a good idea to include the notice in the readme as well.

To avoid having to set the message for each release you can use a range:
```shell
npm deprecate isarray@">=2.0.0" "Just use Array.isArray directly"
```

**Comment by juliangruber** [comment]
thanks! both issues are addressed :)

**Comment by jdalton** [comment]
You rock!

**Comment by juliangruber** [comment]
_You_ rock! 🤘

**Comment by ljharb** [comment]
um, why does this need a deprecation warning at all?

If I'm using `isarray` then I'm explicitly intending to support ES3. All of my modules support ES3, and some of them use isarray, intentionally. Why do they need to have deprecation warnings just because they're trying harder to be backwards compatible then others?

**Comment by jdalton** [comment]
The majority of folks using it had no idea `Array.isArray` was actually supported in Node.
You can always use `@^1.0.0` which doesn't have the deprecation notice.

**Comment by ljharb** [comment]
So those folks just got ES3 support for free, I'm not seeing a problem.

**Comment by jdalton** [comment]
You make shims, that's your thing, of course you don't see a problem 😉

**Comment by ljharb** [comment]
Folks who are bundle-size-sensitive can use browserify shims or webpack aliases to replace `isarray` packages with `Array.isArray`, or they can use a babel transform to convert the same. I don't see why it's a better idea to penalize those who care about back compat, rather than penalize those that are obsessive about bundle size.

**Comment by jdalton** [comment]
In this case back compat is a super niche case of IE < 9 which isn't supported by most folks now-a-days. If you don't want to use `@^1.0.0` of this package you can always create your own (maybe under the es-shim branding).
