### ISSUE TITLE
license discussion  

### ISSUE THREAD

**Issue by calvinmetcalf** [juliangruber/isarray#14]
moved from nodejs/readable-stream#238

**Comment by rwaldron** [comment]
The license is correct, but the _copyright_ should be removed or changed to the rightful author:


- http://ajaxian.com/archives/isarray-why-is-it-so-bloody-hard-to-get-right
- https://web.archive.org/web/20090116062752/http://thinkweb2.com/projects/prototype/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/
- https://github.com/sstephenson/prototype/commit/41b034b93bde78b773af415e45389cbb08cafec4

**Comment by jdalton** [comment]
Naw this is a tangential derail of a thread. @juliangruber wasn't the one stirring up stuff. He acted in good faith with the license, MIT, which is the de facto for many folks releasing software. There's no reason to harass and hound him.

**Comment by rwaldron** [comment]
@jdalton https://github.com/nodejs/readable-stream/pull/238#issuecomment-258083130

This is not "harass, hound or pile". This is delivering valid prior art that clearly illustrates an invalidation of the copyright claim.

**Comment by tobie** [comment]
>  @juliangruber wasn't the one initiating the dust up. He acted in good faith with the licensing and releasing of this package using MIT, which is the de facto for many folks releasing software.

Possibly. But he clearly stopped doing so when asking for 1 million dollars to remove the copyright on code that's neither his nor is copyrightable.

**Comment by jdalton** [comment]
I would have told folks to fuck off so maybe asking for a million was just his way of doing that.

**Comment by tobie** [comment]
For a one-liner that's not even yours? Don't you have better things to do? ;)

**Comment by tobie** [comment]
As an aside, I like how you edit your knee jerk comments to tone them down. Maybe knee jerk commenting isn't the best strategy. WDYT?

**Comment by jdalton** [comment]
> Maybe knee jerk commenting isn't the best strategy. WDYT?

Sure, if you need to low key bully someone, you can go after me instead.

**Comment by tobie** [comment]
O_o

**Comment by rwaldron** [comment]
I'm really confused about the discussion here. @calvinmetcalf opened this to discuss the license issue, and my intention is only to offer relevant historic record of this particular piece of code—nothing more and nothing less.

**Comment by jdalton** [comment]
>  @calvinmetcalf opened this to discuss the license issue

More like to deflect a derailed thread. I get it. But come on.

**Comment by juliangruber** [comment]
There's more to a module than just it's code. It's documentation, the test suite, the build process, the issues, its git history, and so on. Of course I'm not the one who invented this way of checking for an array, and I'm 100% to listing in more detail where it comes from..on the other hand it's as public domain as it gets in JavaScript land.

The 1 Mio thing wasn't serious, but on the other hand it is. The big thing I care about here is for stuff to work. And there's two things that need to work:

1) We need to be able to check if a value is an array, across JavaScript versions. Solved.
2) We need to have sane workflow for module authors putting out their code. Simply stating that since it's a one liner it shouldn't have a license is plain wrong. Inlining it without its license is plain wrong too. That's what bundledDependencies are for, as was already mentioned.

And as @jdalton pointed out, it's deprecated already.

To me, the "solution", is to either rewrite the lib in readable-stream, or use bundled dependencies. What is better is up to readable-stream's maintainers.

And if someone makes valid reasoning that the way the module is licensed is _wrong_, I'm of course happy to change it.

**Comment by OptimusCrime** [comment]
Because they only copied the one single line of code (which is not originally yours), they should not have to adhere to your project license.

Other places where their copied code can be found includes:

- [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)
- [stackoverflow.com #1](https://stackoverflow.com/questions/4775722/check-if-object-is-array)
- [stackoverflow.com $2](https://stackoverflow.com/questions/767486/how-do-you-check-if-a-variable-is-an-array-in-javascript)
- [shamasis.net](http://www.shamasis.net/2011/08/infinite-ways-to-detect-array-in-javascript/)

You get the idea. You created this module, but the line of code does not "belong" to this module itself.

**Comment by Fox2Code** [comment]
Hi, I'm here to clarify the situation for peoples that probably came from [Brodie Robertson video](https://www.youtube.com/watch?v=jRNVEIk61zY)

First a license is a **contract to allow the use of a copyrightable work** for a use that **isn't covered under fair use.**

So if a work is either **non-copyrightable** or covered under **fair use** there is no need to have the license or to respect the term of the license, this include not needing to credit the author.

By following case law of Google vs Oracle where Oracle lost the lawsuit against Google because they used java in Android, it's safe to assume that [`index.js`](https://github.com/juliangruber/isarray/blob/master/index.js) isn't copyrightable and thus don't require the permission of any license to allow the file be copied.

**However,** while the main file of the library is not copyrightable, it's likely that the packaging (Other files around the `index.js`) may be copyrightable, so **I would still recommend respecting the very permissive MIT license when using this library directly.**

I'm not a lawyer so I might have gotten some details wrong, but the general idea of this comment should be accurate.

**Comment by ljharb** [comment]
I'm unclear why this is even still open, so I'll close it.

**Comment by Fox2Code** [comment]
@ljharb I'll think it's better to pin it, as I think it's expected that peoples may still get confused because of the video.
Or at least to put a public message to clear up the confusion.

The last thing I want is a developer getting harassed because of confused GitHub users.

Also I think #27 should be closed too.

**Comment by ljharb** [comment]
@Fox2Code a brand new video, about an issue that was obsolete half a decade ago, from a publisher with a mere 45k subscribers, is something we can handle just fine :-) thanks tho.
