### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by pblackbird** [juliangruber/isarray#27]
Sorry, but I think that it doesn't make any sense, because it's ONE LINE OF CODE. 
Why did you make it as NPM module?

**Comment by ljharb** [comment]
Because older environments don't have `Array.isArray`, and being one line of code doesn't mean it's easy to get right - many people screw up "oneliners".

If you don't want to use it, don't! Many people, however, do, and it's much better for the ecosystem that that's the case.

**Comment by juliangruber** [comment]
> Sorry, but I think that it doesn't make any sense, because it's ONE LINE OF CODE.
> Why did you make it as NPM module?

It sounds like you're making some assumptions that I'm not aware of. Are you worried this costs npm unneccessary money? I don't understand why it's bad to publish a "useless" node module. And as the usage shows, this one is more useful than many more complicated ones.

**Comment by juliangruber** [comment]
I've thought about this a bit more about the weekend..

- Could it be you're mad at other open source modules for including this as a dependency, seemingly bloating up your dependency tree and making it harder to manage?
- Are you confused why such a tiny module can get so important for the ecosystem?
- Are you fearing something like left_pad could happen again, where I delete this module and everything breaks?
- Am I overthinking this and you simply are curious? I read an accusing tome from the all caps "one line of code" in your post

**Comment by l0rb** [comment]
> Are you fearing something like left_pad could happen again, where I delete this module and everything breaks?

this

**Comment by juliangruber** [comment]
> > Are you fearing something like left_pad could happen again, where I delete this module and everything breaks?
> 
> this

That can happen with any other module too. I'm not going to delete it, I already deprecated it and will leave it as is.

**Comment by ljharb** [comment]
That can never happen with any module anymore, since npm no longer allows unpublishes.

**Comment by dustingraham** [comment]
Modules like this constitute one of the pillars of npm. Lots of small hyper focused modules that make up a larger tool. This one alone has 16 million downloads per week. One of the more popular packages on npm.

**Comment by cyb3rturtle** [comment]
@pblackbird привет. не могу отреверсить пасс на твой [крякми](https://anonfile.com/n8x8A81an2/mutant_zip). очень интересно как решается. отпиши в телегу плз @hloyanekroz.

**Comment by ljharb** [comment]
^ that seems to be a spam comment; i suggest not downloading the linked file.

**Comment by cyb3rturtle** [comment]
> ^ that seems to be a spam comment; i suggest not downloading the linked file.

I have no other choice to contact the person since gh doesn't provide any direct message service.

**Comment by ljharb** [comment]
@cyb3rturtle posting a comment in a language that doesn’t match their original post, linking offsite, isn’t likely the best approach. Most GitHub users have a discoverable public email in their commits; additionally, you could always make a repo and invite them to it without causing noise on this thread.

**Comment by juliangruber** [comment]
I reported the comment, which translates to

> Hey. I can’t reverse the pass with your crack. very interesting how it is solved. write to the cart plz @hloyanekroz.

**Comment by PublicByte** [comment]
> Because older environments don't have Array.isArray, and being one line of code doesn't mean it's easy to get right - many people screw up "oneliners".

If you can't trust a developer to write one single line of code then honestly GTFO. The `index.js` file is 4 lines long and you're expecting to me think that you wrote 4 _functioning_ lines of code while you believe I can't even write one line of code correctly.

> Could it be you're mad at other open source modules for including this as a dependency, seemingly bloating up your dependency tree and making it harder to manage? If this is the case, please open issues on the modules _importing_ this one instead.

Yes, and you're indirectly responsible for it. I'd go as far as saying you're encouraging bad habits and enabling "I can't be bothered to think for one second" devs.

> Are you confused why such a tiny module can get so important for the ecosystem?

No, _almost_ nothing can surprise me anymore. I've seen shit that goes well beyond my perceived highest possible value of stupidity and am _trying_ to keep my expectations as low as possible, but it's not fucking possible. There's always someone that manages to be dumber than the previous one and I can't take it anymore. This shit lead to several existential crisis, depression, and self-hatred as I, for my part, am doing a great job at fucking up everything everyone else seems to deal with fine. For fucks sake, just don't write meaningless, useless, unnecessary, counter-productive, bandwidth-, and time wasting garbage hopefully no enterprise will ever have to rely on. I might as well spend the rest of my day going through the dependents list and create a PR to delete this utter trash.

**Comment by juliangruber** [comment]
> If you can't trust a developer to write one single line of code then honestly GTFO.

If you want to discuss with me please use harassment free language.

**Comment by PublicByte** [comment]
> If you want to discuss with me please use harassment free language.

Sorry, as you might've guessed, I can't take this seriously at all. We're talking about a library with no reason to exist, right? How am I supposed to take that seriously?

Especially after hearing…

> many people screw up "oneliners".

You're making this sound like it's the most complicated one-liner in the universe when, in fact, it's probably the easiest and most "unscrewupable" one-liners. The sole existence of this repository is disrespectful and offensive to an astronomically high level that I'm still unsure whether or not this is a troll attempt in a different league.

**Comment by ljharb** [comment]
@PublicByte you'd think that, but I have seen many examples of people screwing it up in their own code.

It's a serious and critical dependency; I use it in many of my projects; the only trollish behavior here is yours.

**Comment by PublicByte** [comment]
@ljharb sad. I guess I've to backpedal if someone actually managed to screw this up.

**Comment by juliangruber** [comment]
I'm open to share my mistakes too, not only have I had to look this or related one-liners up a couple times, I've also messed them up more than once.

**Comment by TheBit** [comment]
Probably everybody read [this](https://www.davidhaney.io/npm-left-pad-have-we-forgotten-how-to-program/) by now, but since there were no mentions, I better post it here (actually I found this piece of engineering from that article). 
You can find in the article several other arguments, like comparison with Java/.Net/other ecosystem, and so that they doesn't practice clustering it into "one-liner" module.
My opinion is that our ecosystem would be better if such one-liners would be combined into bigger utility module, a-la lodash, with design which allows good tree-shaking.

**Comment by ljharb** [comment]
@TheBit tree-shaking only needs to exist when laziness or incompetence has caused too many things to be imported. When you only import the things you need, tree-shaking provides no benefit, because you've already done the bare minimum.

**Comment by Benleie** [comment]
> Sorry, but I think that it doesn't make any sense, because it's ONE LINE OF CODE.
> Why did you make it as NPM module?
Fully agree

**Comment by CharlyJazz** [comment]
This is a good meme

**Comment by jorions** [comment]
Wow the hate on here is baffling. This lib has a narrow use case, but a use case all the same. Raging about an abstract notion of degrading the ecosystem by encouraging laziness because it provides a simple functionality that some people want to use and insulting the author for it is a bizarre channeling of one's time.

Thanks for taking the time to make something that someone finds useful @juliangruber.

**Comment by juliangruber** [comment]
A little background:

I created this module at a time where we were dealing with browsers (this module wasn't targeted at node but to be bundled for browsers) like older internet explorers, which didn't ship with their own implementation of `Array.isArray`. I've worked in multiple code bases that needed an `isArray` implementation, so it made sense to have some kind of shared solution, so it would just work.

Using _polyfills_ was a common practice at that time, however it had the big drawback that library code shouldn't install them as they could conflict with each other, or even override existing implementations of `Array.isArray` provided by the browser. If you want to offer your code in a library, you also don't want to tell your consumers to install polyfills. Therefore, we started using _ponyfills_, which exposed the logic in need without changing the surrounding environment. This module is a ponyfill. Following this logic, you could say that the primary use case was library authors, however for application authors it could be just as useful.

Now comes the question of why one wouldn't just repeat the code over and over, and to me that has obvious problems, most notably: You can get it wrong, you can copy an implementation that has bugs, and you can clutter your codebase with these helper functions. If you publish _a lot_ of modules, as I did at this time, it was always safer to `npm install isarray` than to write it yourself, and quicker and _tidier_ than placing this helper function somewhere in your codebase. Using a package manager like npm, it would also result in a smaller bundle size, because if say 20 modules use a similar version of `isArray` then that code would only end up in your production build once, and not 20 times.

Besides, this library doesn't ask to be used. There was never any promotion run for it. You can see it being popular however, so you have to ask yourself which advantage it brought to its many consumers. Doesn't its download count more than anything validate its purpose, and indicate that you might not be in touch with needs that developers had at that time?

**Comment by juliangruber** [comment]
And maybe, I shouldn't forget to mention: I too wish this module didn't need to exist. But, this was the best solution to me at that time.

**Comment by 06kellyjac** [comment]
$710 is up for grabs if you do ever fancy deleting this :sweat_smile:

https://drewdevault.com/2021/11/16/Cash-for-leftpad.html

I'm not going to put my opinion as to whether you should or not because it doesn't matter what I think

**Comment by Rudxain** [comment]
I think we may need a `CODE_OF_CONDUCT.md` file

**Comment by FunctionDJ** [comment]
It's okay and good that this package exists and all of us should work hard to update dependencies to not rely on this.
To everyone that has built up rage over the JavaScript ecosystem within them: turn it into something productive and make a PR to a repo that could live without this dependency.

**Comment by CharlyJazz** [comment]
> I dont want to offend anybody but you guys are retarded

The word "retarded" is not politically correct

**Comment by pankajthekush** [comment]
This is useless pile of 4 line code created to increase bloat or the auther could feel superior.

**Comment by ljharb** [comment]
@pankajthekush if you actually read the thread, you'd see why it's critical and useful. Please avoid hostile, toxic comments.

**Comment by coomdev** [comment]
If I were to play devil's advocate here, this package only supports Node's module system, CommonJS. Meaning only JS code running on a node environment can use this package (and that's not even considering that npm versions that are that old may not be able to even successfully pull this package due to all the possible api breakage possible).
However isArray got implemented into v8 back in early-2010, this package dates back to 2013.
Node got its initial release back in mid-2009, this means that node was without the standard isArray for the first 6 months of its existence at most, and this package was introduced when node was 7 times older than the version that already had isArray builtin, so there wasn't, at any moment in this package existence, any real reason to install it.
Also if I were to nitpick, I wouldn't use toString and instead use the instanceof operator for obvious performance and semantical reasons.

So this begs the question, has anyone ever demonstrated a use case for this package?

**Comment by kartofen** [comment]
> The word "retarded" is not politically correct
It was the only word powerful enough to express my feelings about the creators and maintainers of this package

**Comment by ljharb** [comment]
@kartofen in that case, next time choose *not to express them*.

**Comment by ljharb** [comment]
@coomdev the devil doesn't need an advocate; ESM modules in node can import CJS; everything in the ecosystem can use a bundler to consume CJS. The other reason is that developers support *browsers* that lacked `Array.isArray`.

The other reason is that `delete Array.isArray` will break everyone who *isn't* using this package. Robustness matters.

**Comment by coomdev** [comment]
@ljharb it still doesn't make sense, supporting browsers that old is a massive cost sink espectially considering they only run on OS that don't receive security update anymore and core-js already provides that and many more other polyfills.

**Comment by kartofen** [comment]
@ljharb how much more money do you need for the transition?

**Comment by juliangruber** [comment]
It used to make sense supporting these browsers. Now this project only exists for legacy reasons.

**Comment by laurachopsuey** [comment]
Ich liebe Monopole und Gatekeep Bosses, @juliangruber single?

**Comment by ljharb** [comment]
I still use it for evergreen reasons - robustness, to protect against folks monkeying with `Array` after my module has been evaluated.

@coomdev it costs nothing; this problem is solved.

@kartofen it's not about money, i will need it forever for this reason.

**Comment by kartofen** [comment]
> Ich liebe Monopole und Gatekeep Bosses, @juliangruber single?

Wir muessen die Juden ausrotten

**Comment by ljharb** [comment]
@kartofen hopefully github will now remove you for your Nazi hate speech.

**Comment by juliangruber** [comment]
I have already reported the comment for hate speech

**Comment by kartofen** [comment]
I hope github will remove you for begin retarded

**Comment by kartofen** [comment]
I would rather die on my feet than live on my knees

**Comment by ljharb** [comment]
@CharlyJazz feel free to delete https://github.com/juliangruber/isarray/issues/27#issuecomment-1292327152 now that the user has been removed
@juliangruber feel free to delete https://github.com/juliangruber/isarray/issues/27#issuecomment-1292600458 now that the user has been removed.

i'll hide this comment for now, and i'll delete this comment once both of you have deleted yours :-)

**Comment by KotlinIsland** [comment]
Could someone please publish a `notIsArray` package. For secity reason, thanks.

**Comment by Rudxain** [comment]
> Could someone please publish a `notIsArray` package.

```js
'use strict';
const
    bruh = require('isarray'),
    notIsArray = x => !bruh(x);
module.exports = notIsArray;
```

> For secity reason, thanks.

IDK if this helps for security, but I used `const` instead of `let`

**Comment by juliangruber** [comment]
this already exists https://github.com/zlatinejc/isnotarray

**Comment by juliangruber** [comment]
Since I was just reminded of this: isarray was used to build parts of the Nintendo Switch: https://twitter.com/janl/status/1594427116372000769.

**Comment by Rudxain** [comment]
> [...] can't trust a developer to write one single line [...]

Not everyone is a dev. Some people are just coders/programmers. That might sound "elitist", but it's the truth. Here's an analogy: developers are architects, coders know how to write or draw basic shapes.

> [...] easiest and most "unscrewupable" [sic][...]

What does this code do?
```js
const mystery = x => (y => typeof y == typeof x && y === x % y ** y)(x ^ x)
```
It's just a [PF](https://en.wikipedia.org/wiki/Purely_functional_programming) one-liner, it should be easy to understand!

Need something "familiar"? Here's a hint:
```js
const mystery = x => {
    const z = x^x
    if (typeof x != typeof z)
        return false
    const o = z**z
    return x % o === z
}
```
Still don't understand? How about now?
```js
/**
Check if `x` is any primitive integer.
@param {unknown} x
*/
const is_prim_int = x => {
    /** auto-type zero */
    const n0 = x ^ x

    // is `x` non-numeric?
    if (typeof x != typeof n0)
        return false

    /** auto-type one */
    const n1 = n0 ** n0

    // elegantly handles edge-cases
    // such as `NaN` and `Infinity`
    return x % n1 === n0
}
```

See how even the most basic (as in "foundational" or "essential") of code can be not-so-straightforward?

One could argue the code should be rewritten as:
```js
function is_primitive_integer(x) {
    if (typeof x === 'bigint') {
        return true;
    };
    return Number.isInteger(x);
}
```
Note how "readable code" isn't always appropriate:
- `===` is unlikely to get minified to `==`
- It sacrifices future-proofing, as it only handles `Number` and `BigInt`, rendering it useless for [`BigFloat`](https://github.com/tc39/proposal-decimal).
- It directly depends on a global-object method, making it prone to monkey-patching.
